"Status: Fixed":
  comment: |-
    :wave: @{issue-author},

    This issue has been fixed in the [latest build](https://ci.pluginwiki.us/job/SimplePets_v5/) or in a future build that will be released soon!
  issues:
    close: true

fixed in v5:
  comment: |-
    :wave: @{issue-author},

    This has already been fixed in v5! Please update to the latest version to get the fix.
    Downloads:
    - [Spigot](https://www.spigotmc.org/resources/100106/)
    - [Polymart](https://polymart.org/resource/1952/)
    - [Jenkins](https://ci.pluginwiki.us/job/SimplePets_v5/)
  issues:
    close: true

"Type: Bug":
  comment: |-
    @{issue-author},

    Thank you for reporting this bug, we will try and respond as soon as we can to your issue.
    In the meantime have a look at the [WIKI](https://brainsynder.gitbook.io/simplepets/) to see if we made any mention to it on there.

"Status: Missing Debug Log":
  comment: |-
    @{issue-author},

    You seem to be missing the debug log, this is required to help us find any plugin conflicts, addon issues, and outdated versions.
    You can comment or edit your post with the link generated from `/pet debug` (It will generate a `pastelog.us` link)

    Note: If the link does not generate then you can upload the `plugins/SimplePets/debug.json` file to an alternate site (like pastebin)

"Status: Unsupported Version":
  comment: |-
    @{issue-author},

    Your issue is based on an unsupported version of either Minecraft or SimplePets.
    Please use up-to-date version and get back to us once you have tried it out on the latest versions.

Added in Latest Build:
  comment: >
    @{issue-author}, This was added in the latest build of SimplePets you can download the jar from the [Jenkins Server](https://ci.pluginwiki.us/job/SimplePets_v5/)
  issues:
    close: true

"Status: Blame Mojang":
  comment: >
    @{issue-author}, This is regarded as a Mojang issue we have no control over this.
  issues:
    close: true

"Status: Needs More Info":
  comment: |-
    @{issue-author}, We need to collect a little more information regarding this issue.
    If this is a bug report: Please provide additional information to help us figure out what is happening
    If this is a feature request: Please provide more information on what you would like requested

"Status: Unable to Reproduce":
  comment: |-
    @{issue-author},

    Unfortunately we were unable to reproduce your issue.
    Please provided more information regarding this issue such as:
    - Your `/pet debug` link (Link generated after you run the command)
    - Your `latest.log` (Or the log file that was around the time of the issue)
    - Minecraft Version
    - Spigot/Paper Version
    - Video Evidence?
    - Images?

"Status: Answered":
  issues:
    close: true

"Status: Completed":
  issues:
    close: true
