<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>simplepets.brainsynder</groupId>
    <artifactId>SimplePets</artifactId>
    <version>1</version>
    <packaging>pom</packaging>

    <properties>
        <!-- These 2 values are used by my Update Checker to check for new dev builds -->
        <jenkins.name>SimplePets_v5</jenkins.name>
        <jenkins.buildNumber>0</jenkins.buildNumber>

        <module.info>-parent</module.info>
        <revision>5.0-BUILD-0</revision>

        <java.version>17</java.version>
        <bslib.version>B144</bslib.version>
        <anvilgui.version>1.10.4-SNAPSHOT</anvilgui.version>
        <spigotupdatechecker.version>3.0.3</spigotupdatechecker.version>
        <protocol-lib.version>5.0.0</protocol-lib.version>
        <commons-io.version>2.11.0</commons-io.version>
        <specialsource.version>2.0.4</specialsource.version>
        <shade.version>3.5.0</shade.version>

        <minecraft.version>1.21.11</minecraft.version>
        <spigot.version>${minecraft.version}-R0.1-SNAPSHOT</spigot.version>
        <spigot.nms>v1_21_R7</spigot.nms>

        <!-- Used to compile specific versions -->
        <target-mc>${minecraft.version}</target-mc>

        <current-module.version/>
        <current-module.nms/>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>

    <profiles>
        <!-- Used to compile a selected version Example: mvn clean install -Dtarget-mc=1.20.4 -->
        <profile>
            <id>targeted</id>
            <activation>
                <property>
                    <name>target-mc</name>
                </property>
            </activation>

            <modules>
                <module>plugin-api</module>
                <module>plugin-core</module>
                <module>plugin-distribution</module>

                <module>nms/master</module>
                <module>nms/version-${target-mc}</module>
            </modules>
        </profile>


        <!-- Used to compile for the latest mc version Example: mvn clean install -Platest -->
        <profile>
            <id>latest</id>

            <modules>
                <module>plugin-api</module>
                <module>plugin-core</module>
                <module>plugin-distribution</module>

                <module>nms/master</module>
                <module>nms/version-${minecraft.version}</module>
            </modules>
        </profile>


        <!-- Used to compile for the 1.19 mc versions Example: mvn clean install -P1.19 -->
        <profile>
            <id>1.19</id>

            <modules>
                <module>plugin-api</module>
                <module>plugin-core</module>
                <module>plugin-distribution</module>

                <module>nms/version-1.19</module>
                <module>nms/version-1.19.1</module>
                <module>nms/version-1.19.2</module>
                <module>nms/version-1.19.3</module>
                <module>nms/version-1.19.4</module>
            </modules>
        </profile>


        <!-- Used to compile for the 1.20 mc versions Example: mvn clean install -P1.20 -->
        <profile>
            <id>1.20</id>

            <modules>
                <module>plugin-api</module>
                <module>plugin-core</module>
                <module>plugin-distribution</module>

                <module>nms/version-1.20</module>
                <module>nms/version-1.20.1</module>
                <module>nms/version-1.20.2</module>
                <module>nms/version-1.20.3</module>
                <module>nms/version-1.20.4</module>
                <module>nms/version-1.20.5</module>
                <module>nms/version-1.20.6</module>
            </modules>
        </profile>


        <!-- Used to compile for the 1.21 mc versions Example: mvn clean install -P1.21 -->
        <profile>
            <id>1.21</id>

            <modules>
                <module>plugin-api</module>
                <module>plugin-core</module>
                <module>plugin-distribution</module>

                <module>nms/version-1.21</module>
                <module>nms/version-1.21.1</module>
                <module>nms/version-1.21.3</module>
                <module>nms/version-1.21.4</module>
                <module>nms/version-1.21.5</module>
                <module>nms/version-1.21.6</module>
                <module>nms/version-1.21.7</module>
                <module>nms/version-1.21.8</module>
                <module>nms/version-1.21.9</module>
                <module>nms/version-1.21.10</module>
                <module>nms/version-1.21.11</module>
            </modules>
        </profile>

        <!-- This profile is automatically run when running the 'mvn clean install' command -->
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <modules>
                <module>plugin-api</module>
                <module>plugin-core</module>
                <module>plugin-distribution</module>

                <module>nms/master</module>

                <module>nms/version-1.21.6</module>
                <module>nms/version-1.21.7</module>
                <module>nms/version-1.21.8</module>
                <module>nms/version-1.21.10</module>
                <module>nms/version-1.21.11</module>
                <!-- AUTOMATION: INSERTION POINT -->
            </modules>

            <build>
                <resources>
                    <resource>
                        <directory>${project.basedir}/resources/</directory>
                        <filtering>true</filtering>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>lib.brainsynder</groupId>
            <artifactId>API</artifactId>
            <version>${bslib.version}</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>bs-repo-nms</id>
            <url>https://repo.bsdevelopment.org/nms</url>
        </repository>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>bs-repo-releases</id>
            <url>https://repo.bsdevelopment.org/releases</url>
        </repository>
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/nexus/repository/public/</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
        <repository>
            <id>jeff-media-public</id>
            <url>https://repo.jeff-media.com/public/</url>
        </repository>
        <repository>
            <id>devmart-other</id>
            <url>https://nexuslite.gcnt.net/repos/other/</url>
        </repository>
    </repositories>

    <build>
        <defaultGoal>clean install</defaultGoal>
        <finalName>${project.parent.artifactId}${module.info}</finalName>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.0.0</version>

                <configuration>
                    <updatePomFile>true</updatePomFile>
                </configuration>

                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.15.0</version>
                <configuration>
                    <groupId>simplepets.brainsynder</groupId>

                    <properties>
                        <property>
                            <name>revision</name>
                        </property>
                        <property>
                            <name>spigot.version</name>
                        </property>
                        <property>
                            <name>minecraft.version</name>
                        </property>
                        <property>
                            <name>java.version</name>
                        </property>
                        <property>
                            <name>shade.version</name>
                        </property>
                        <property>
                            <name>compiler.version</name>
                        </property>
                        <property>
                            <name>anvilgui.version</name>
                        </property>
                        <property>
                            <name>module.version</name>
                        </property>
                        <property>
                            <name>bslib.version</name>
                        </property>
                        <property>
                            <name>spigotupdatechecker.version</name>
                        </property>
                        <property>
                            <name>protocol-lib.version</name>
                        </property>
                        <property>
                            <name>commons-io.version</name>
                        </property>
                        <property>
                            <name>specialsource.version</name>
                        </property>
                        <property>
                            <name>target-mc</name>
                        </property>
                    </properties>
                </configuration>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${shade.version}</version>
                    <configuration>
                        <minimizeJar>false</minimizeJar>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                        <shadedArtifactAttached>false</shadedArtifactAttached>
                        <outputDirectory>/tmp</outputDirectory>

                        <relocations>
                            <relocation>
                                <pattern>${project.groupId}.nms</pattern>
                                <shadedPattern>${project.groupId}.versions.${current-module.version}</shadedPattern>
                            </relocation>
                            <relocation>
                                <pattern>org.bukkit.craftbukkit.${spigot.nms}</pattern>
                                <shadedPattern>org.bukkit.craftbukkit.${current-module.nms}</shadedPattern>
                            </relocation>

                            <relocation>
                                <pattern>org.apache.commons.io</pattern>
                                <shadedPattern>${project.groupId}.internal.apache</shadedPattern>
                            </relocation>
                            <relocation>
                                <pattern>net.wesjd</pattern>
                                <shadedPattern>${project.groupId}.internal.anvil</shadedPattern>
                            </relocation>
                            <relocation>
                                <pattern>io.papermc.lib</pattern>
                                <shadedPattern>${project.groupId}.internal.papermc</shadedPattern>
                            </relocation>
                            <relocation>
                                <pattern>com.jeff_media.updatechecker</pattern>
                                <shadedPattern>${project.groupId}.internal.updatechecker</shadedPattern>
                            </relocation>
                        </relocations>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>shade</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <distributionManagement>
        <repository>
            <id>bs-repo-releases</id>
            <url>https://repo.bsdevelopment.org/releases</url>
        </repository>
    </distributionManagement>
</project>