<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>simplepets.brainsynder</groupId>
        <artifactId>SimplePets</artifactId>
        <version>1</version>
    </parent>

    <artifactId>MAIN</artifactId>
    <version>${revision}</version>

    <build>
        <sourceDirectory>src/</sourceDirectory>

        <resources>
            <resource>
                <directory>${project.basedir}/../resources/</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.yml</include>
                    <include>*.properties</include>
                    <include>*.txt</include>
                </includes>
            </resource>
        </resources>


        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${shade.version}</version>
                <configuration>
                    <minimizeJar>false</minimizeJar>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>false</shadedArtifactAttached>
                    <outputDirectory>/tmp</outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>org.apache.commons</pattern>
                                    <shadedPattern>${project.groupId}.internal.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.wesjd</pattern>
                                    <shadedPattern>${project.groupId}.internal.anvil</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.papermc.lib</pattern>
                                    <shadedPattern>${project.groupId}.internal.papermc</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.jeff_media.updatechecker</pattern>
                                    <shadedPattern>${project.groupId}.internal.updatechecker</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <shadedPattern>${project.groupId}.internal.bstats</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <properties>
        <module.info>-IGNORE</module.info>
        <minecraft.version>1.21.6</minecraft.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>simplepets.brainsynder</groupId>
            <artifactId>API</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.0.2</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.jeff_media</groupId>
            <artifactId>SpigotUpdateChecker</artifactId>
            <version>${spigotupdatechecker.version}</version> <!-- Check on GitHub for the latest version -->
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>

        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>${protocol-lib.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.tcoded</groupId>
            <artifactId>FoliaLib</artifactId>
            <version>0.2.3</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>