<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>simplepets.brainsynder</groupId>
        <artifactId>SimplePets</artifactId>
        <version>1</version>
    </parent>

    <artifactId>DIST</artifactId>
    <version>${revision}</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <finalName>SimplePets</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>package-all</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>all-jar.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${shade.version}</version>
                <configuration>
                    <minimizeJar>false</minimizeJar>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>false</shadedArtifactAttached>
                    <outputDirectory>/tmp</outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>org.apache.commons.io</pattern>
                                    <shadedPattern>${project.groupId}.internal.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.wesjd</pattern>
                                    <shadedPattern>${project.groupId}.internal.anvil</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.papermc.lib</pattern>
                                    <shadedPattern>${project.groupId}.internal.papermc</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.jeff_media.updatechecker</pattern>
                                    <shadedPattern>${project.groupId}.internal.updatechecker</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <configuration>
                            <target>
                                <copy file="${project.build.directory}/${project.build.finalName}.jar"
                                      todir="../run/plugins/"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <properties>
        <module.info/>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>${anvilgui.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <!-- Used to compile only the 1.19 MC versions  -->
            <id>1.19</id>

            <dependencies>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.19</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.19.1</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.19.2</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.19.3</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.19.4</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <!-- Used to compile only the 1.20 MC versions  -->
            <id>1.20</id>

            <dependencies>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20.1</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20.2</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20.3</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20.4</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20.5</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.20.6</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <!-- Used to compile only the 1.21 MC versions  -->
            <id>1.21</id>

            <dependencies>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.1</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.3</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.4</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.5</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.6</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.7</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.8</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.11</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <!-- Used to compile only the latest MC version  -->
            <id>latest</id>

            <dependencies>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_${minecraft.version}</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <!-- Used to compile only the latest MC version  -->
            <id>targeted</id>
            <activation>
                <property>
                    <name>target-mc</name>
                </property>
            </activation>

            <dependencies>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_${target-mc}</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>


        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <dependencies>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.6</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.7</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.8</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.10</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>simplepets.brainsynder</groupId>
                    <artifactId>Version_1.21.11</artifactId>
                    <version>${revision}</version>
                    <scope>compile</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>net.wesjd</groupId>
                            <artifactId>anvilgui</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.bstats</groupId>
                            <artifactId>bstats-bukkit</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>simplepets.brainsynder</groupId>
                            <artifactId>NMS_Master</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <!-- AUTOMATION: INSERTION POINT -->
            </dependencies>
        </profile>
    </profiles>
</project>